### ISSUE TITLE
No named form element

### ISSUE THREAD

**Issue by hawkett** [PolymerElements/gold-cc-expiration-input#23] opened 2015-07-14 21:09 UTC
When supplying a 'name' attribute to gold-cc-expiration-input, it does not appear to be reflected on any contained html form element. Consequently it is not possible to get a value using ```form.<element_name>.value```

Realise there is some complexity here given that there are actually 2 inputs, but it's a little unintuitive given that other form elements do not have this behaviour/constraint. Perhaps there should be a hidden form element whose name/value achieve the desired outcome?

**Comment by notwaldorf** [comment] 2015-07-14 21:46
@hawkett What is `form.value`? `gold-cc-expiration-input` has a value, and it's the entered date. If you check [this](http://meowni.ca/polymer-gold-elements-demo/index.html) demo and you submit the first form, the json submitted is:
```
{ "cc-cvc": "123", "cc-expiration": "11/22", "cc-number": "4000 0000 0000 0002", "name": "Batman"
```
and the expiration looks fine. Do you have some code or a jsbin that reproduces the problem?

**Comment by hawkett** [comment] 2015-07-14 22:31
Apologies - I didn't markup my code properly in the OP so ```<element_name>``` didn't appear in the original question - fixed in OP.

Agree there is a value on ```gold-cc-expiration-input```, but it is not an actual HTML form element so ```form.<element_name>.value`` doesn't resolve to anything.

**Comment by notwaldorf** [comment] 2015-07-14 23:24
Hahaha, oh forms. I didn't know that was a thing. :(

I don't think that will ever (easily) work in an `iron-form`. `form[name]` is api magic that indexes into the form's `elements` array. We can't hijack the `[` operator, and I don't think we want to insert custom elements into the form's `elements` array.

You can certainly use a hidden input in your form (the one that is using the `gold-cc-expiration-input`, and  set its value to the expiration-input's one. Unfortunately, we can't add it inside the `gold-cc-expiration-input` itself, since that won't be visible in the shadow DOM.

Just out of curiosity, what's the use case for this? Like, when do you actually use `form.name.value` (vs, say, `form.querySelector('#elementid').value`)

**Comment by hawkett** [comment] 2015-07-15 19:07
Haha. I started making sure I had names on my elements in response to [this issue](https://github.com/PolymerElements/iron-form/issues/28)

I stopped using ids for form elements for a couple of reasons:
* The redundancy of: ```<input id="name" name="name" label="name" title="name" placeholder="name" .... ``` was doing my head in. I guess I'm exaggerating a little there for effect, but you get my drift. It was already annoying me, and then I needed to add 'name' for validation to work, and I cracked :)
* I casually try to avoid using the 'id' attribute when I don't need it. It's not a strongly held pattern, but shady DOM not providing true boundaries against duplicate ids, and [issues like this](https://github.com/Polymer/polymer/issues/2057) give some idea of why.
* [This discussion](http://stackoverflow.com/questions/2435525/best-practice-access-form-elements-by-html-id-or-name-attribute) is relevant. An interesting comment there is that ```id``` is needed for labels to work correctly, so I guess the paper ```label``` is helping me out in that regard.

I can cope with using ids if I need to.

Re. the form's elements array - at this stage, the only component I've run into issues with is this one, because it doesn't actually name a real html form element. All the others (e.g. paper-input) I've been using create a real child ```<input>``` with the provided name whose value is set correctly, so those elements will appear in the form's elements array. I guess this is currently working due to Shady DOM rather than Shadow DOM.

This leads to a fairly interesting discussion (depending on your definition of interesting) about Form and Shadow DOM. While I'm all for the idea that the Shadow DOM is a strict encapsulation boundary from which nothing can escape, I'm not sure I'm comfortable with the idea that this means we can't create Web Components that interact natively with forms (e.g. appear in the elements array). The most obvious answer is that such a component *must* extend native form elements, like ```<iron-input>``` does, but that seems  limiting. Perhaps the browser implementation of Shadow DOM *should* pierce the Shadow DOM for the purpose of populating the form's ```elements``` object. Doing so would allow much more flexibility in the definition of custom form elements. I'm sure this or similar issue have been considered many times with more care than I'm currently giving it.

I think probably the right answer here is for me to go back to using ids - name referencing is sounding... less reliable. Now if only I didn't need to name my form elements to get them to validate :)

**Comment by notwaldorf** [comment] 2015-07-15 19:37
So Shadow DOM aside, the reason why we made `iron-form` is that the native form only tracks `<input>`. So unless your custom elements contains an `<input>`, you'll have a hard time convincing a native form to care. This is already true of other native elements like `<div>` and `<p>` which are not form controls and get ignored for a living.

Once `<iron-form>` exists, though, we now have the option to track any custom element, provided it implements a specific behaviour, so that it can tell the `iron-form` that it's the kind of element that belongs in a form. This we do here: https://github.com/PolymerElements/iron-form/blob/master/iron-form.html#L117. 

I didn't put the custom elements in the native form's `elements` array because `<form>` is a black box of magic, I don't know how it's implemented and how often that array gets sorted/stomped over/etc.

Also, did some more digging. `querySelector` is magical and the answer to everything, and you don't need ids: `form.querySelectorAll("[name='name']")` is totally a thing. I know it's more verbose though, but at least you don't need an id? Sigh.

**Comment by hawkett** [comment] 2015-07-15 19:52
querySelectorAll() supports all css selectors as far as I'm aware. I prefer this.$.name for conciseness, with the bonus that it's likely faster.

**Comment by notwaldorf** [comment] 2015-08-17 22:10
@hawkett I'm going to close this issue, since I'm afraid there's nothing that we can do here: `form.<element_name>.value` only works for native elements, and I don't see how it can work for custom elements.

**Closed by notwaldorf** 2015-08-17 22:10 UTC
